Repository iPriceGroup/info, pull requests merged in 2020-08, with the labels that each got.

#318 Change moe hk look and hide data and popup
  hk/mapofecommerce/index.html
Labels: size/S

#322 Remove /e from sg URL
  sg/mapofecommerce/index.html
Labels: size/XS

#323 Change HongKong to Hong Kong
  hk/mapofecommerce/index.html
  id/mapofecommerce/en/index.html
  id/mapofecommerce/index.html
  my/mapofecommerce/en/index.html
  my/mapofecommerce/index.html
  ph/mapofecommerce/en/index.html
  ph/mapofecommerce/index.html
  sg/mapofecommerce/index.html
  th/mapofecommerce/en/index.html
  th/mapofecommerce/index.html
  vn/mapofecommerce/en/index.html
  vn/mapofecommerce/index.html
Labels: size/M

#324 IP-16119: Fix MOE popup delay
  hk/mapofecommerce/index.html
  id/mapofecommerce/en/index.html
  id/mapofecommerce/index.html
  my/mapofecommerce/en/index.html
  my/mapofecommerce/index.html
  ph/mapofecommerce/en/index.html
  ph/mapofecommerce/index.html
  sg/mapofecommerce/index.html
  th/mapofecommerce/en/index.html
  th/mapofecommerce/index.html
  vn/mapofecommerce/en/index.html
  vn/mapofecommerce/index.html
Labels: size/L

#315 IP-16337: Update links to Hong Kong from other domains
  id/mapofecommerce/index.html
  my/mapofecommerce/index.html
  ph/mapofecommerce/index.html
  sg/mapofecommerce/index.html
  th/mapofecommerce/index.html
  vn/mapofecommerce/index.html
Labels: size/L
