Repository iPriceGroup/info, pull requests merged in 2020-02, with the labels that each got.

#288 Enhance scrolling popup
  id/mapofecommerce/en/index.html
  id/mapofecommerce/index.html
  my/mapofecommerce/en/index.html
  my/mapofecommerce/index.html
  ph/mapofecommerce/en/index.html
  ph/mapofecommerce/index.html
  sg/mapofecommerce/index.html
  th/mapofecommerce/en/index.html
  th/mapofecommerce/index.html
  vn/mapofecommerce/en/index.html
  vn/mapofecommerce/index.html
Labels: size/L

#289 change jotform link and height
  id/mapofecommerce/en/index.html
  id/mapofecommerce/index.html
  my/mapofecommerce/en/index.html
  my/mapofecommerce/index.html
  ph/mapofecommerce/en/index.html
  ph/mapofecommerce/index.html
  sg/mapofecommerce/index.html
  th/mapofecommerce/en/index.html
  th/mapofecommerce/index.html
  vn/mapofecommerce/en/index.html
  vn/mapofecommerce/index.html
Labels: size/M

#290 Fix vn link to moe
  vn/mapofecommerce/en/index.html
Labels: size/XS

#291 Change list of merchants context
  vn/mapofecommerce/en/index.html
Labels: size/S

#292 IP-12608: UX change to the Map of eCommerce (MoE) (#292)
  id/mapofecommerce/en/index.html
  id/mapofecommerce/index.html
  my/mapofecommerce/en/index.html
  my/mapofecommerce/index.html
  ph/mapofecommerce/en/index.html
  ph/mapofecommerce/index.html
  sg/mapofecommerce/index.html
  th/mapofecommerce/en/index.html
  th/mapofecommerce/index.html
  vn/mapofecommerce/en/index.html
  vn/mapofecommerce/index.html
Labels: size/M

#293 Add q4 data to vn
  hk/mapofecommerce/iframe/data/translation.json
  hk/mapofecommerce/iframe/data/vn/q4-2019.json
Labels: size/XL
