Repository iPriceGroup/info, pull requests merged in 2020-07, with the labels that each got.

#307 Mapping CSV to Json
  hk/mapofecommerce/qaiframe/assets/js/apps.js
  hk/mapofecommerce/qaiframe/data/dummy/id/2019-q3-merchant.csv
  hk/mapofecommerce/qaiframe/data/dummy/id/2019-q4-merchant.csv
  hk/mapofecommerce/qaiframe/data/dummy/id/2020-q1-merchant.csv
  hk/mapofecommerce/qaiframe/data/dummy/merchant-data.xml
  hk/mapofecommerce/qaiframe/index.html
Labels: size/XXL

#308 Using real data
  hk/mapofecommerce/qaiframe/assets/js/apps.js
  hk/mapofecommerce/qaiframe/data/dummy/merchant-data.xml
Labels: size/L

#309 Add business model
  hk/mapofecommerce/qaiframe/assets/js/apps.js
  hk/mapofecommerce/qaiframe/data/translation.json
Labels: size/M

#306 IP-15688: Generate iFrame from S3 data
  hk/mapofecommerce/qaiframe/assets/js/apps.js
  hk/mapofecommerce/qaiframe/assets/js/papaparse.min.js
  hk/mapofecommerce/qaiframe/data/dummy/id/2019-q3-merchant.csv
  hk/mapofecommerce/qaiframe/data/dummy/id/2019-q4-merchant.csv
  hk/mapofecommerce/qaiframe/data/dummy/id/2020-q1-merchant.csv
  hk/mapofecommerce/qaiframe/data/dummy/merchant-data.xml
  hk/mapofecommerce/qaiframe/data/translation.json
  hk/mapofecommerce/qaiframe/index.html
  id/mapofecommerce/en/index.html
  id/mapofecommerce/index.html
  my/mapofecommerce/en/index.html
  my/mapofecommerce/index.html
  ph/mapofecommerce/en/index.html
  ph/mapofecommerce/imgs/logo/desktop/iherb.png
  ph/mapofecommerce/index.html
  sg/mapofecommerce/index.html
  th/mapofecommerce/en/index.html
  th/mapofecommerce/imgs/logo/desktop/globalhouse.png
  th/mapofecommerce/index.html
  vn/mapofecommerce/en/index.html
  vn/mapofecommerce/imgs/logo/desktop/lixibox.png
  vn/mapofecommerce/index.html
Labels: size/XXL

#311 Fix youtube, line color scale effect
  hk/mapofecommerce/qaiframe/assets/js/apps.js
Labels: size/S

#313 Add parm for appsjs
  hk/mapofecommerce/iframe/assets/js/apps.js
  hk/mapofecommerce/iframe/index.html
Labels: size/XS
